### ISSUE TITLE
Textdraws are always white

### ISSUE THREAD

**Issue by Andonrai** [dockfries/infernus#21]
I'm creating a textdraw, but it doesn't matter what color I put on it, it's always white, and if I try to get the color with getBoxColour(), it returns undefined.

Code used to create the textdraw
![](https://imgur.com/jndY60P.png)

Result
![](https://imgur.com/lH5qzHZ.png)

**Comment by dockfries** [comment]
After examining [omp-stdlib](https://github.com/openmultiplayer/omp-stdlib/blob/master/omp_textdraw.inc), it appears that certain deprecated natives are only being redirected through their original names instead of being replaced with entirely new native functions.   This issue will be addressed in the upcoming release of `@infernus/core`.


```c
#pragma deprecated Use `TextDrawColour`
native bool:TextDrawColor(Text:textid, textColour);

#pragma deprecated Use `PlayerTextDrawColour`
native bool:PlayerTextDrawColor(playerid, PlayerText:textid, textColour);

```

**Comment by dockfries** [comment]
See also [TextDrawBackgroundColor](https://www.open.mp/zh-cn/docs/scripting/functions/TextDrawBackgroundColor).
**When both background and color are used, only the former is applied.**
**Try upgrading `@infernus/core` to 0.9.1**
