### ISSUE TITLE
Add samp-cef

### ISSUE THREAD

**Issue by cha5e369** [dockfries/infernus#34]
Is it possible that in the not too distant future [samp-cef](https://github.com/Pycckue-Bnepeg/samp-cef?tab=readme-ov-file) will be added in Infernus? It would be very useful in terms of new interfaces that we could develop.

**Comment by dockfries** [comment]
I'm not sure it will work properly. First of all, omp should be compatible with samp-cef.

Assuming it is compatible, if it can be implemented, I think there will be some changes in the workflow of `cef_subscribe`, because the callback of `cef_subscribe` must exist in the `.pwn` code, and different event correspond to different callbacks and cannot be aggregated in the same callback, so `cef_emit_event` still needs to be executed in `.pwn` code.

Or in the corresponding callback, through the samp_node api `SAMPNode_CallEvent`, into the callback that we manually registered through `samp.on`, and then emit_event at the javascript level?
