### ISSUE TITLE
@infernus/cef

### ISSUE THREAD

**Issue by lyricsdev** [dockfries/infernus#36]
hey bro i have a problem with that
when i'm trying to emit event to show player a ui server giving that ```[dev:server] [2024-05-26T00:19:34+0300] [Info] [sampgdk:w] Invalid buffer size```
can i have your discord to show problem properly? didnt find any yours contacts
p.s
on calling event 
```
CefEvent.onInitialize(({ player, success, next }) => {
  if (!player) return next();

  if (success) {
    new Cef({
      player,
      browserId: 1,
      url: "http://localhost:7779",
      hidden: false,
      focused: true,
    });
  } else {
    player.sendClientMessage(
      -1,
      "Ahh to bad you cannot see our new cool interface ...",
    );
  }

  return next();
});
```
its getting [dev:server] [2024-05-26T01:53:36+0300] [Info] [sampgdk:w] Invalid buffer size
but if we are calling like in docs samp-cef it works(pawn)

**Comment by dockfries** [comment]
try using the latest `@infernus/cef@^0.1.0` with the [polyfill](https://github.com/dockfries/infernus-starter/tree/main/gamemodes?rgh-link-date=2024-05-26T08%3A55%3A44Z) of cef available in infernus-starter.

can you specifically post the code of emitEvent?

**Comment by lyricsdev** [comment]
recreated a project with 0.1.0 semp cef
Now it works but so stange. it shows me only when i press and only after when i going to window mode and back 
![image](https://github.com/dockfries/infernus/assets/77627599/95947cfb-5f77-4307-94d6-887df268aa3c)
[example](https://youtu.be/QPQkQPgrMGQ)

**Comment by dockfries** [comment]
This is really strange. The case I provide is always shown. Have you tried to develop your current cef code by pawn? I think it may be a problem at the sa client level.

The orm library like prisma is not fully supported by samp-node at present. 
I have tried to use typeorm, and I almost always encounter blocking terminal execution every time I start, which is strange, but press enter, but this is obviously not suitable for actual production environments.

The blocking problem is not caused by infernus and needs to be solved by samp-node authors.

**Comment by lyricsdev** [comment]
yep i tried it works normally :D, so i can provide to u a zip file with that to test by your self, maybe its trouble in my client? cef 1.4.1

**Comment by dockfries** [comment]
Sure, I used 1.4.1 too

**Comment by lyricsdev** [comment]
can i have your discord or telegram to provide? or for you will be easyli to get invited to repo?

**Comment by dockfries** [comment]
discord: dockfries2233
